trigger:
- master

pool:
  name: flm-pool

steps:
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonar-server'
    scannerMode: 'other'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'